# Generated by Django 5.1.7 on 2025-03-21 23:20

import django.db.models.deletion
import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_professores_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='disciplinas_lecionadas',
        ),
        migrations.RemoveField(
            model_name='professores',
            name='disciplinas_lecionadas',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='professores',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, unique=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(related_name='alunos', to='alunos.disciplina'),
        ),
        migrations.AddField(
            model_name='professores',
            name='disciplinas',
            field=models.ManyToManyField(related_name='professores', to='alunos.disciplina'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.turma')),
            ],
        ),
    ]
