# Generated by Django 5.1.7 on 2025-03-21 23:58

import alunos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_disciplina_remove_aluno_disciplinas_lecionadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professores',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01', validators=[alunos.validators.validate_data_nascimento]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(validators=[alunos.validators.validate_data_nascimento]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(max_length=20, validators=[alunos.validators.validate_telefone]),
        ),
        migrations.AlterField(
            model_name='professores',
            name='telefone',
            field=models.CharField(max_length=20, validators=[alunos.validators.validate_telefone]),
        ),
    ]
